# Generated by Django 4.1.4 on 2022-12-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_project_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="portfolio/images/"),
        ),
    ]
